### PR TITLE
custom Sorting of Names, Codes, etc

### PR DESCRIPTION
**Pull request by epuzanov**
…objects

This PR adds support for customizable elements (Names, Codes, Moieties, etc) sorting order with configurable comparators for CommonDataElementOfCollection objects.

### CODE REVIEW

**Comment by ChemMitch** [comment]
Looks like a very useful change

**Comment by dkatzel-ncats** [comment]
This is a nice idea but I might make a couple of design changes:
1. I never liked the "with" parameter.  Newer parts of the code use Jackson to set arbitrary pojo fields so you can still have parameters just not a "with" Map. 
2. I don't know if requiring entities and GinasCommonData to implement Comparable is a good idea.  It might be better to not have that requirement and rely on the Util.getComparator() method to look for the comparator that was registered, and if not found use the natural default comparator if the object is comparable and if not do not sort it.  it would keep the old code as is and allow others to add sorts if they wanted.

**Comment by dkatzel-ncats** [comment]
@epuzanov  I made a few changes to make it more consistent with how we tried to do configurations in gsrs 2.5+ and more importantly in 3.0.  Basically, instead of a "with" map, I renamed it  parameters to be consistent with other newer configuration classes and the keys in that map are now field names in your implementation class.  Then Java Bean conventions let us automatically call the setters via Jackson.  I also removed the static fields to be instance methods (and static default values if needed) so we don't share and change state across instances.

Finally, I moved the configuration to the `gsrs-core.conf` instead of `ginas.conf` so others can inherit it in their own custom confs.

If this looks OK to you I will merge.

**Comment by epuzanov** [comment]
Yes. This is Ok. I will use this approach for the future development too.

**Review by dkatzel-ncats — DISMISSED** [review]

**Review by dkatzel-ncats — APPROVED** [review]

**Pull request merged**
